library(lubridate)
library(tidyr)
library(ggplot2)
library(gsheet)
library(tictoc)
library(data.table)
library(dplyr)

source("/Volumes/BZ/Scientific Data/RG-AS04-Data01/R_tracking_analysis/scripts/tracking_analysis_functions.R")

## Set the directory to the '_analysis2' folder, or wherever all of the als files are located
setwd("/Volumes/BZ/Scientific Data/RG-AS04-Data01/LCP/_analysis2/")

####### LOAD IN GOOGLE SHEET DATA #######

# The following loads in the meta data from the google sheet. The url is the same as the 'share' link (generated by the share button in google sheets)
# This uses two functions - 'read.csv', which is a base R function, and 'gsheet2text' which comes from package 'gsheet'

url <- 'https://docs.google.com/spreadsheets/d/1IU6dzH7gYW5OgLho26Nu9IfQ9D4nIqGG4y6XEY0fAH8/edit?usp=sharing'
meta_data <- read.csv(text=gsheet2text(url, format='csv'), stringsAsFactors=FALSE)

# You can use 'dim()' or 'head()' to quickly examine the results dataframe to see if it's correct
dim(meta_data)
head(meta_data)

####### IDENTIFY THE FILES FOR IMPORT #######

# List the files in the current directory that are als files
als.files <- list.files(path = ".", recursive = TRUE, pattern = "_als.csv")


####### RUN THE COMMANDS TO IMPORT DATA ########

# This imports a single file (the 10th file path) and summarises by minute
als.data <- loadALSfiles(path_to_file = als.files[10], average_by = "minute")

# This takes a single dataset and further summarises it by halfhour (probably not so useful, but can save space/computation time)
als.data.2 <- summariseALSdata(als_data = als.data, average_by = "halfhour")

# This averages by day for a single dataset
# Importantly, ignore the single entry for day 1 when setting 'days_include'. For example, if you want the first 3 days, do 'days_include = c(1,2,3)' NOT 'days_include = c(2,3,4)'
avg.day <- averageDay(als_data = als.data.2, units = "halfhour", days_include = "all")


######## RUN COMMANDS FOR PLOTTING ########

# Can you '+ geom_rect_shading_bz' or '+ geom_rect_shading_zoo' to add shading based on times
# Colours can be specified with '+ shade_colours()' which uses grey/yellow/white colour scheme (can make your own)

ggplot(avg.day, aes(x = datetime, y = mean_speed_mm)) + geom_rect_shading_bz() + shade_colours() + geom_point() + geom_line()


######## COMMANDS FOR MULTIPLE DATASETS & ADDING META_DATA & PLOTTING ########

# This imports a list of files
als.data.list <- lapply(als.files, function(x) loadALSfiles(path_to_file = x, average_by = "minute"))

## Can then save out the files for re-use
saveRDS(als.data.list, file = "als_data_list.rds")

als.data.list <- readRDS("als_data_list.rds")

# ... and then averages across days by halfhour
avg.day.list <- lapply(als.data.list, function(x) averageDay(als_data = x, units = "halfhour", days_include = "all"))

# Reduce the list into one dataframe
avg.day.combined <- Reduce(rbind, avg.day.list)

# Add meta_data
avg.day.combined <- merge(avg.day.combined, meta_data, by = "sample_id")

## Then plot
plot <- ggplot(avg.day.combined, aes(x = datetime, y = mean_speed_mm, group = sample_id, color = shell)) + geom_rect_shading_bz() + geom_point() + geom_line() + theme_classic()

## Use 'facet_wrap' to separate based on columns in meta_data
## works like an equation ~ means 'by', and you can use addition ('shell+strain' or 'strain+conspecifics')
plot + shade_colours() + facet_wrap(~shell+conspecifics, ncol = 2)


plot + shade_colours() + facet_wrap(~conspecifics, ncol = 2)
plot + shade_colours() + facet_wrap(~shell, ncol = 2)












